name: Synchronize Issue Labels

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  milestone:
    if: github.repository_owner == 'ory'
    name: Synchronize Issue Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Synchronize Issue Labels
        uses: ory/label-sync-action@f080c2b8ac988f2fc90ddbbc8749c6ee55477f21
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          dry: false
          forced: true
